### ISSUE TITLE
ICSP和TweakScale冲突

### ISSUE THREAD

**Issue by LittleMonster12138** [Armo00/NCAP#7]
[BUG.zip](https://github.com/Armo00/NCAP/files/8933350/BUG.zip)，
ICSP和TweakScale冲突，进游戏开始页面报错。有时候会出现原本降落伞、RCS，MOD消失不见。但是会正常工作

**Comment by Armo00** [comment]
Mod列表：
![QQ截图20220618175001](https://user-images.githubusercontent.com/17452430/174433519-6b207fe7-931e-4e6f-a189-828351c5c5e7.png)
游戏界面截图：
![QQ截图20220618180726](https://user-images.githubusercontent.com/17452430/174433522-91841bf4-1e7f-4641-bc63-5478857e6de1.png)
MM日志文件：
[ModuleManager.zip](https://github.com/Armo00/NCAP/files/8933361/ModuleManager.zip)
KSP.log文件：
暂无
