### ISSUE TITLE
ICSP和TweakScale冲突

### ISSUE THREAD

**Issue by LittleMonster12138** [Armo00/NCAP#8]
ICSP和TweakScale冲突，进游戏开始页面报错。有时候会出现原本降落伞、RCS，MOD消失不见。但是会正常工作
Mod列表：
![QQ截图20220618175001](https://user-images.githubusercontent.com/106045013/174433861-129883e5-f830-4ada-9392-f7ef70da3c23.png)
游戏界面截图：
![QQ截图20220618180726](https://user-images.githubusercontent.com/106045013/174433868-38ecf21f-7c8b-45b1-8420-1ad090f9daf5.png)
MM日志文件：
[ModuleManager.zip](https://github.com/Armo00/NCAP/files/8933376/ModuleManager.zip)

**Comment by Armo00** [comment]
已解决
